language: node_js

node_js:
  - "6"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g hexo-cli

script:
  - hexo generate

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change