language: node_js

node_js:
  - "8"

branches:
  only:
    - master

script:
  - npm run validate

before_deploy:
  - npm run gen:speakers
  - npx hexo generate

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "QNQTBgyL3uG2k/GA04U1oenJzdZQ48WkUZN3QYvSufC4MOgQClNjCD0yFkYGQGrZvACDdqAp/OTFEIYGLStYJdBxwWImB5SYfSkejS8r2/Anz2qpvAFtoB/GQ41YUan7dp162jHXtpV9cKE3i8gYgd0w2q8nSVDTfnVXpndH9o/06c+8U6Na2HGdWE11oEYH1Lgb6n5HYp/yejuzYt9FGMYqmCYa1f5chMRQzF6Xh3H323kEhyRJcJTdGWe1jmFgB5ySC97Smlns0Nak3Y073NZPrpnJCWNbSa2uprCbFNsKgK7Gs+01ibTahaT2DsB8x+WImVVyBdGvmkPtVoD24PzJlj1xrgG6bCxny9YYPoZJ5CvE3rPt2LS3Ny3NzkVzQlNXndjmV9h4MGdL9ACslu6eqiGzsrYidHXOXtL8JJuiWdnmA1K6kfHsdi1UCYU1aWYvetda+mhfeQm3lzUBJSLnpL6bEWcRx6oY84/Zz2MAW0wkwHJPOMc3Qy+JnqsSPQOI9XgjYdil9s4GQPLEKznhpx8+E5SIsMJdinoHrWDyuapB70DioSPzkgxLPekItlJaB88neQwI9hhUxSHX2C2sGwVVBqRmrKip74mbrhvy/DLTOj0DwsEl0Mwgl5V4ne3qwydIuN6rV3juO4qmaOBKqN8By4h31GqNiqLoeJE="

notifications:
  email:
    on_failure: change
    on_success: change
